package project.models;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : project.models.Game.java
//  @ Date : 4/30/2026
//  @ Author : 
//
//

import java.util.Map;

public class Game {
    public int matchID;
    public Map<String, Hero> players;
    public ETeam winningTeam;

    public Game() {}

    public Game(int matchID, Map<String, Hero> players, ETeam winningTeam) {
        this.matchID = matchID;
        this.players = players;
        this.winningTeam = winningTeam;
    }
}
