package project.models;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : project.models.Game.java
//  @ Date : 4/30/2026
//  @ Author : 
//
//




public class Game {
    public int matchID;
    public Map<String, *Hero> players;
    public ETeam winningTeam;
}
