package project.models;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : project.models.Hero.java
//  @ Date : 4/30/2026
//  @ Author : 
//
//




public class Hero {
    public String name;
    private int wins;
    private int totalGames;
    public String adminComment;
    public void updateStats(int wins, int losses) {
    
    }
}
