package project.models;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : project.models.Hero.java
//  @ Date : 4/30/2026
//  @ Author : 
//
//

public class Hero {
    public String name;
    private int wins;
    private int totalGames;
    public String adminComment;

    public Hero() {}

    public Hero(String name) {
        this.name = name;
    }

    public void updateStats(int wins, int losses) {
        this.wins += wins;
        this.totalGames += (wins + losses);
    }

    public int getWins() {
        return wins;
    }

    public void setWins(int wins) {
        this.wins = wins;
    }

    public int getTotalGames() {
        return totalGames;
    }

    public void setTotalGames(int totalGames) {
        this.totalGames = totalGames;
    }
}
