package project.models;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : project.models.HeroTierlist.java
//  @ Date : 4/30/2026
//  @ Author : 
//
//




public class HeroTierlist {
    public Map<String, List<Hero>> ranks;
    public void updateFromWinrates(IGameRepository gamesRepo) {
    
    }
}
