package project.models;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : project.models.User.java
//  @ Date : 4/30/2026
//  @ Author : 
//
//




public class User {
    public String username;
    private String password;
    private int id;
    private bool isAdmin = false;
    public bool getIsAdmin() {
    
    }
}
