//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Backend.java
//  @ Date : 4/30/2026
//  @ Author : 
//
//




public class Backend {
    private IUserRepository userRepo;
    private IGamesRepository gameRepo;
    private IHeroRepository heroRepo;
    private HeroTierlist heroTierlist;
    public User login(Object user, Object password) {
    
    }
    
    public void register(Object user, Object password) {
    
    }
    
    public void importGames(List<Games> games) {
    
    }
    
    public void getHeroTierlist() {
    
    }
    
    public void updateHeroTierlist() {
    
    }
}
