//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Menu.java
//  @ Date : 4/30/2026
//  @ Author : 
//
//




public class Menu {
    private EMenuState state = EMenuState.SelectLoginRegister;
    private Backend backend;
    private User loggedInUser;
    public void Menu(Backend backend) {
    
    }
    
    public void display() {
    
    }
    
    public void logout() {
    
    }
}
