package project.repositories;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : project.repositories.GamesRepositoryJson.java
//  @ Date : 4/30/2026
//  @ Author :
//
//

import org.json.JSONArray;
import org.json.JSONObject;
import org.json.JSONTokener;
import project.models.ETeam;
import project.models.Game;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class GamesRepositoryJson implements IGamesRepository {
    private final Map<Integer, Game> games = new HashMap<>();
    private final String filePath;

    public GamesRepositoryJson(String filePath) {
        this.filePath = filePath;
        load();
    }

    private void load() {
        File file = new File(filePath);
        if (!file.exists()) {
            return;
        }
        try (FileInputStream fis = new FileInputStream(file)) {
            JSONTokener tokener = new JSONTokener(fis);
            if (!tokener.more()) {
                return;
            }
            JSONObject root = new JSONObject(tokener);
            for (String matchIDKey : root.keySet()) {
                JSONObject obj = root.getJSONObject(matchIDKey);
                Game game = new Game();
                game.matchID = obj.getInt("matchID");
                game.winningTeam = ETeam.valueOf(obj.getString("winningTeam"));
                
                Map<String, Game.PlayerStats> players = new HashMap<>();
                if (obj.has("teams")) {
                    JSONObject teamsObj = obj.getJSONObject("teams");
                    for (String teamName : teamsObj.keySet()) {
                        ETeam team = ETeam.valueOf(teamName);
                        JSONObject teamPlayers = teamsObj.getJSONObject(teamName);
                        for (String username : teamPlayers.keySet()) {
                            JSONObject statsObj = teamPlayers.getJSONObject(username);
                            Game.PlayerStats stats = new Game.PlayerStats();
                            stats.heroName = statsObj.getString("heroName");
                            stats.kills = statsObj.getInt("kills");
                            stats.deaths = statsObj.getInt("deaths");
                            stats.assists = statsObj.getInt("assists");
                            stats.team = team;
                            players.put(username, stats);
                        }
                    }
                }
                game.players = players;
                games.put(game.matchID, game);
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    private void save() {
        JSONObject root = new JSONObject();
        for (Game game : games.values()) {
            JSONObject obj = new JSONObject();
            obj.put("matchID", game.matchID);
            obj.put("winningTeam", game.winningTeam.name());
            
            JSONObject teamsObj = new JSONObject();
            teamsObj.put("HiddenKing", new JSONObject());
            teamsObj.put("ArchMother", new JSONObject());
            
            for (Map.Entry<String, Game.PlayerStats> entry : game.players.entrySet()) {
                Game.PlayerStats stats = entry.getValue();
                JSONObject statsObj = new JSONObject();
                statsObj.put("heroName", stats.heroName);
                statsObj.put("kills", stats.kills);
                statsObj.put("deaths", stats.deaths);
                statsObj.put("assists", stats.assists);
                
                String teamName = stats.team.name();
                if (!teamsObj.has(teamName)) {
                    teamsObj.put(teamName, new JSONObject());
                }
                teamsObj.getJSONObject(teamName).put(entry.getKey(), statsObj);
            }
            obj.put("teams", teamsObj);
            root.put(String.valueOf(game.matchID), obj);
        }
        try (FileWriter writer = new FileWriter(filePath)) {
            writer.write(root.toString(4));
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    @Override
    public List<Game> getGames() {
        return new ArrayList<>(games.values());
    }

    @Override
    public void importGames(List<Game> gamesToImport) {
        for (Game game : gamesToImport) {
            games.put(game.matchID, game);
        }
        save();
    }

    @Override
    public int getGameCount() {
        return games.size();
    }

    @Override
    public void clear() {
        games.clear();
        save();
    }
}
