package project.repositories;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : project.repositories.GamesRepositoryJson.java
//  @ Date : 4/30/2026
//  @ Author : 
//
//

import org.json.JSONArray;
import org.json.JSONObject;
import org.json.JSONTokener;
import project.models.ETeam;
import project.models.Game;
import project.models.Hero;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class GamesRepositoryJson implements IGamesRepository {
    private Map<Integer, Game> games = new HashMap<>();
    private String filePath;

    public GamesRepositoryJson(String filePath) {
        this.filePath = filePath;
        load();
    }

    private void load() {
        File file = new File(filePath);
        if (!file.exists()) {
            return;
        }
        try (FileInputStream fis = new FileInputStream(file)) {
            JSONArray array = new JSONArray(new JSONTokener(fis));
            for (int i = 0; i < array.length(); i++) {
                JSONObject obj = array.getJSONObject(i);
                Game game = new Game();
                game.matchID = obj.getInt("matchID");
                game.winningTeam = ETeam.valueOf(obj.getString("winningTeam"));
                
                JSONObject playersObj = obj.getJSONObject("players");
                Map<String, Hero> players = new HashMap<>();
                for (String key : playersObj.keySet()) {
                    JSONObject heroObj = playersObj.getJSONObject(key);
                    Hero hero = new Hero();
                    hero.name = heroObj.getString("name");
                    hero.setWins(heroObj.getInt("wins"));
                    hero.setTotalGames(heroObj.getInt("totalGames"));
                    if (heroObj.has("adminComment")) {
                        hero.adminComment = heroObj.getString("adminComment");
                    }
                    players.put(key, hero);
                }
                game.players = players;
                games.put(game.matchID, game);
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    private void save() {
        JSONArray array = new JSONArray();
        for (Game game : games.values()) {
            JSONObject obj = new JSONObject();
            obj.put("matchID", game.matchID);
            obj.put("winningTeam", game.winningTeam.name());
            
            JSONObject playersObj = new JSONObject();
            for (Map.Entry<String, Hero> entry : game.players.entrySet()) {
                Hero hero = entry.getValue();
                JSONObject heroObj = new JSONObject();
                heroObj.put("name", hero.name);
                heroObj.put("wins", hero.getWins());
                heroObj.put("totalGames", hero.getTotalGames());
                heroObj.put("adminComment", hero.adminComment);
                playersObj.put(entry.getKey(), heroObj);
            }
            obj.put("players", playersObj);
            array.put(obj);
        }
        try (FileWriter writer = new FileWriter(filePath)) {
            writer.write(array.toString(4));
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    @Override
    public List<Game> getGames() {
        return new ArrayList<>(games.values());
    }

    @Override
    public void importGames(List<Game> gamesToImport) {
        for (Game game : gamesToImport) {
            games.put(game.matchID, game);
        }
        save();
    }

    @Override
    public int getGameCount() {
        return games.size();
    }
}
