package project.repositories;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : project.repositories.GamesRepositoryJson.java
//  @ Date : 4/30/2026
//  @ Author : 
//
//




public class GamesRepositoryJson implements IGamesRepository {
    private Map<int, Game> games;
    private String filePath;
}
