package project.repositories;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : project.repositories.HeroRepositoryJson.java
//  @ Date : 4/30/2026
//  @ Author : 
//
//

import org.json.JSONArray;
import org.json.JSONObject;
import org.json.JSONTokener;
import project.models.Hero;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;

public class HeroRepositoryJson implements IHeroRepository {
    private Map<String, Hero> heroes = new HashMap<>();
    private String filePath;

    public HeroRepositoryJson(String filePath) {
        this.filePath = filePath;
        load();
    }

    private void load() {
        File file = new File(filePath);
        if (!file.exists()) {
            return;
        }
        try (FileInputStream fis = new FileInputStream(file)) {
            JSONArray array = new JSONArray(new JSONTokener(fis));
            for (int i = 0; i < array.length(); i++) {
                JSONObject obj = array.getJSONObject(i);
                Hero hero = new Hero();
                hero.name = obj.getString("name");
                hero.setWins(obj.getInt("wins"));
                hero.setTotalGames(obj.getInt("totalGames"));
                if (obj.has("adminComment")) {
                    hero.adminComment = obj.getString("adminComment");
                }
                heroes.put(hero.name, hero);
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    private void save() {
        JSONArray array = new JSONArray();
        for (Hero hero : heroes.values()) {
            JSONObject obj = new JSONObject();
            obj.put("name", hero.name);
            obj.put("wins", hero.getWins());
            obj.put("totalGames", hero.getTotalGames());
            obj.put("adminComment", hero.adminComment);
            array.put(obj);
        }
        try (FileWriter writer = new FileWriter(filePath)) {
            writer.write(array.toString(4));
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    @Override
    public Map<String, Hero> getHeroes() {
        return heroes;
    }

    @Override
    public void updateHero(Hero hero) {
        heroes.put(hero.name, hero);
        save();
    }
}
