package project.repositories;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : project.repositories.HeroRepositoryJson.java
//  @ Date : 4/30/2026
//  @ Author : 
//
//




public class HeroRepositoryJson implements IHeroRepository {
    private List<Hero> heroes;
    private String filePath;
}
