package project.repositories;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : project.repositories.HeroRepositoryJson.java
//  @ Date : 4/30/2026
//  @ Author :
//
//

import org.json.JSONObject;
import org.json.JSONTokener;
import project.models.Hero;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;

public class HeroRepositoryJson implements IHeroRepository {
    private Map<String, Hero> heroes = new HashMap<>();
    private String filePath;

    public HeroRepositoryJson(String filePath) {
        this.filePath = filePath;
        load();
    }

    private void load() {
        File file = new File(filePath);
        if (!file.exists()) {
            return;
        }
        try (FileInputStream fis = new FileInputStream(file)) {
            JSONTokener tokener = new JSONTokener(fis);
            if (!tokener.more()) {
                return;
            }
            JSONObject root = new JSONObject(tokener);
            for (String key : root.keySet()) {
                JSONObject obj = root.getJSONObject(key);
                Hero hero = new Hero();
                hero.name = key;
                hero.setWins(obj.getInt("wins"));
                hero.setTotalGames(obj.getInt("totalGames"));
                hero.setTotalKills(obj.optInt("totalKills", 0));
                hero.setTotalDeaths(obj.optInt("totalDeaths", 0));
                hero.setTotalAssists(obj.optInt("totalAssists", 0));
                hero.adminComment = obj.optString("adminComment", "");
                heroes.put(hero.name, hero);
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    private void save() {
        JSONObject root = new JSONObject();
        for (Hero hero : heroes.values()) {
            JSONObject obj = new JSONObject();
            obj.put("wins", hero.getWins());
            obj.put("totalGames", hero.getTotalGames());
            obj.put("totalKills", hero.getTotalKills());
            obj.put("totalDeaths", hero.getTotalDeaths());
            obj.put("totalAssists", hero.getTotalAssists());
            obj.put("adminComment", hero.adminComment != null ? hero.adminComment : "");
            root.put(hero.name, obj);
        }
        try (FileWriter writer = new FileWriter(filePath)) {
            writer.write(root.toString(4));
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    @Override
    public Map<String, Hero> getHeroes() {
        return heroes;
    }

    @Override
    public void updateHero(Hero hero) {
        heroes.put(hero.name, hero);
        save();
    }

    @Override
    public void clear() {
        heroes.clear();
        save();
    }
}
