package project.repositories;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : project.repositories.IGamesRepository.java
//  @ Date : 4/30/2026
//  @ Author : 
//
//

import project.models.Game;
import java.util.List;

public interface IGamesRepository {
    List<Game> getGames();
    void importGames(List<Game> games);
    int getGameCount();
}
