package project.repositories;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : project.repositories.IGamesRepository.java
//  @ Date : 4/30/2026
//  @ Author : 
//
//




public class IGamesRepository {
    private void load() {
    
    }
    
    private void save() {
    
    }
    
    public List<Game> getGames() {
    
    }
    
    public void importGames(List<Game> games) {
    
    }
    
    public int getGameCount() {
    
    }
}
