package project.repositories;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : project.repositories.IHeroRepository.java
//  @ Date : 4/30/2026
//  @ Author : 
//
//




public class IHeroRepository {
    private void load() {
    
    }
    
    private void save() {
    
    }
    
    public Map<String, Hero> getHeroes() {
    
    }
    
    public void updateHero(Object hero) {
    
    }
}
