package project.repositories;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : project.repositories.IHeroRepository.java
//  @ Date : 4/30/2026
//  @ Author : 
//
//

import project.models.Hero;
import java.util.Map;

public interface IHeroRepository {
    Map<String, Hero> getHeroes();
    void updateHero(Hero hero);
}
