package project.repositories;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : project.repositories.IUserRepository.java
//  @ Date : 4/30/2026
//  @ Author :
//
//

import project.models.User;

public interface IUserRepository {
    void addUser(String username, String hashedPassword);
    User authenticate(String username, String password);
    User getUser(String username);
    void updateUser(User user);
}
