package project.repositories;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : project.repositories.IUserRepository.java
//  @ Date : 4/30/2026
//  @ Author : 
//
//




public class IUserRepository {
    private void load() {
    
    }
    
    private void save() {
    
    }
    
    public void addUser(String username, String hashedPassword) {
    
    }
    
    public void authenticate(String username, String password) {
    
    }
}
