package project.repositories;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : project.repositories.UserRepositoryJson.java
//  @ Date : 4/30/2026
//  @ Author : 
//
//




public class UserRepositoryJson extends IUserRepository implements IUserRepository {
    private Map<String, User> users;
    private String filePath;
}
