package project.repositories;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : project.repositories.UserRepositoryJson.java
//  @ Date : 4/30/2026
//  @ Author :
//
//

import org.json.JSONObject;
import org.json.JSONTokener;
import org.mindrot.jbcrypt.BCrypt;
import project.models.User;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;

public class UserRepositoryJson implements IUserRepository {
    private final Map<String, User> users = new HashMap<>();
    private final String filePath;

    public UserRepositoryJson(String filePath) {
        this.filePath = filePath;
        load();
    }

    private void load() {
        File file = new File(filePath);
        if (!file.exists()) {
            return;
        }
        try (FileInputStream fis = new FileInputStream(file)) {
            JSONTokener tokener = new JSONTokener(fis);
            if (!tokener.more()) {
                return;
            }
            JSONObject root = new JSONObject(tokener);
            for (String key : root.keySet()) {
                JSONObject obj = root.getJSONObject(key);
                User user = new User(
                        obj.getString("username"),
                        obj.getString("password"),
                        obj.getInt("id"),
                        obj.getBoolean("isAdmin")
                );
                users.put(user.username, user);
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    private void save() {
        JSONObject root = new JSONObject();
        for (User user : users.values()) {
            JSONObject obj = new JSONObject();
            obj.put("username", user.username);
            obj.put("password", user.getPassword());
            obj.put("id", user.getId());
            obj.put("isAdmin", user.getIsAdmin());
            root.put(String.valueOf(user.getId()), obj);
        }
        try (FileWriter writer = new FileWriter(filePath)) {
            writer.write(root.toString(4));
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    @Override
    public void addUser(String username, String password) {
        if (users.containsKey(username)) {
            return;
        }
        int nextId = users.size() + 1;
        String hashedPassword = BCrypt.hashpw(password, BCrypt.gensalt());
        User user = new User(username, hashedPassword, nextId, false);
        users.put(username, user);
        save();
    }

    @Override
    public User authenticate(String username, String password) {
        User user = users.get(username);
        if (user != null && BCrypt.checkpw(password, user.getPassword())) {
            return user;
        }
        return null;
    }

    @Override
    public User getUser(String username) {
        return users.get(username);
    }

    @Override
    public void updateUser(User user) {
        if (users.containsKey(user.username)) {
            users.put(user.username, user);
            save();
        }
    }
}
